export const cryptoData = [
    {
        id: 1,
        name: "Solana",
        ticker: "SOL",
        holdings: "$304.56",
        amount: "24 SOL",
        profitPercentage: "+0.07%",
        profitValue: "+$2",
        profitColor: "text-green-500",
        logo: "https://cryptologos.cc/logos/solana-sol-logo.svg?v=035",
        flag: true,
        coinId: 'solana',
    },
    {
        id: 2,
        name: "USDC",
        ticker: "USDC",
        holdings: "$304.56",
        amount: "24 LTC",
        profitPercentage: "-0.35%",
        profitValue: "+$2",
        profitColor: "text-red-500",
        logo: "https://cryptologos.cc/logos/usd-coin-usdc-logo.svg?v=035",
        flag: true,
        coinId: 'usd-coin',
    },
    {
        id: 3,
        name: "MUMU",
        ticker: "MUMU",
        mint: '5LafQUrVco6o7KMz42eqVEJ9LW31StPyGjeeu5sKoMtA',
        holdings: "0.0",
        amount: "0.0",
        profitPercentage: "0.0%",
        profitValue: "$0",
        profitColor: "text-gray-500",
        logo: "https://tokeninsight.com/cdn-cgi/image/width=140,height=140,format=webp,quality=100,fit=cover/https://s2.tokeninsight.com/static/coins/img/currency/Mumu_MUMU.png",
        flag: false,
        coinId: 'bitcoin',
    },
    {
        id: 4,
        name: "USDT",
        ticker: "USDT",
        holdings: "0.0",
        amount: "0.0",
        profitPercentage: "0.0%",
        profitValue: "$0",
        profitColor: "text-gray-500",
        logo: "https://cryptologos.cc/logos/tether-usdt-logo.svg?v=035",
        flag: true,
        coinId: 'ethereum',
    },
    {
        id: 5,
        name: "Raydium",
        ticker: "Raydium",
        holdings: "0.0",
        amount: "0.0",
        profitPercentage: "0.0%",
        profitValue: "$0",
        profitColor: "text-gray-500",
        logo: "/src/assets/Raydium.svg",
        flag: true,
        coinId: 'raydium',
    },
];